/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CzVfBeePDok
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuCheckboxItem,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export function ACourses() {
  const courses = [
    {
      id: 1,
      title: "Introduction to Web Development",
      description:
        "Learn the fundamentals of HTML, CSS, and JavaScript to build modern websites.",
      image: "/img/web.png?height=200&width=300",
      category: "Web Development",
      difficulty: "Beginner",
      price: 49.99,
    },
    {
      id: 2,
      title: "Python for Data Analysis",
      description:
        "Dive into the world of data analysis and visualization using Python and its powerful libraries.",
      image: "/img/python.png?height=200&width=300",
      category: "Data Science",
      difficulty: "Intermediate",
      price: 79.99,
    },
    {
      id: 3,
      title: "Mastering React.js",
      description:
        "Become a proficient React developer and learn to build complex, scalable web applications.",
      image: "/img/react-performance.jpg?height=200&width=300",
      category: "Web Development",
      difficulty: "Advanced",
      price: 99.99,
    },
    {
      id: 4,
      title: "Introduction to Machine Learning",
      description:
        "Explore the fundamentals of machine learning and build your own predictive models.",
      image: "/img/machinelen.png?height=200&width=300",
      category: "Data Science",
      difficulty: "Intermediate",
      price: 69.99,
    },
    {
      id: 5,
      title: "Responsive Web Design",
      description:
        "Learn to create websites that adapt seamlessly to different devices and screen sizes.",
      image: "/img/responsive.png?height=200&width=300",
      category: "Web Development",
      difficulty: "Beginner",
      price: 59.99,
    },
    {
      id: 6,
      title: "Advanced SQL Techniques",
      description:
        "Dive deep into SQL and master complex queries, optimization, and database management.",
      image: "/img/9775751_1599214921_SQL (2).jpg?height=200&width=300",
      category: "Data Science",
      difficulty: "Advanced",
      price: 89.99,
    },
  ];
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [selectedDifficulty, setSelectedDifficulty] = useState("all");
  const filteredCourses = useMemo(() => {
    return courses.filter((course) => {
      if (selectedCategory !== "all" && course.category !== selectedCategory) {
        return false;
      }
      if (
        selectedDifficulty !== "all" &&
        course.difficulty !== selectedDifficulty
      ) {
        return false;
      }
      return true;
    });
  }, [selectedCategory, selectedDifficulty]);
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center justify-between px-4 lg:px-8 h-14 border-b">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">Acme Inc</span>
        </Link>
        <nav className="flex items-center gap-4 sm:gap-6">
          <Link
            href="/auth"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Home
          </Link>
          <Link
            href="/auth/ACourses"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Courses
          </Link>
          <Link
            href="/auth/About"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            About
          </Link>
          <Link
            href="/auth/cart"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Cart
          </Link>
        </nav>
      </header>
      <section className="bg-primary text-primary-foreground py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6 text-center">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
            Unlock Your Potential with Our Courses
          </h1>
          <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
            Explore a wide range of courses across various subjects and skill
            levels. Enroll today and start your journey to success.
          </p>
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary-foreground px-8 text-sm font-medium text-primary shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 mt-6"
            prefetch={false}
          >
            Browse Courses
          </Link>
        </div>
      </section>
      <section className="py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col md:flex-row items-center justify-between mb-8">
            <div className="grid gap-2">
              <h2 className="text-2xl font-bold">All Courses</h2>
              <p className="text-muted-foreground">
                Explore our wide range of courses and find the perfect one for
                you.
              </p>
            </div>
            <div className="flex gap-4 mt-4 md:mt-0">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" className="flex items-center gap-2">
                    <FilterIcon className="h-4 w-4" />
                    <span>Filter by Category</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuLabel>Category</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuCheckboxItem
                    checked={selectedCategory === "all"}
                    onCheckedChange={() => setSelectedCategory("all")}
                  >
                    All
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedCategory === "Web Development"}
                    onCheckedChange={() =>
                      setSelectedCategory("Web Development")
                    }
                  >
                    Web Development
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedCategory === "Data Science"}
                    onCheckedChange={() => setSelectedCategory("Data Science")}
                  >
                    Data Science
                  </DropdownMenuCheckboxItem>
                </DropdownMenuContent>
              </DropdownMenu>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" className="flex items-center gap-2">
                    <FilterIcon className="h-4 w-4" />
                    <span>Filter by Difficulty</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuLabel>Difficulty</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuCheckboxItem
                    checked={selectedDifficulty === "all"}
                    onCheckedChange={() => setSelectedDifficulty("all")}
                  >
                    All
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedDifficulty === "Beginner"}
                    onCheckedChange={() => setSelectedDifficulty("Beginner")}
                  >
                    Beginner
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedDifficulty === "Intermediate"}
                    onCheckedChange={() =>
                      setSelectedDifficulty("Intermediate")
                    }
                  >
                    Intermediate
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedDifficulty === "Advanced"}
                    onCheckedChange={() => setSelectedDifficulty("Advanced")}
                  >
                    Advanced
                  </DropdownMenuCheckboxItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {filteredCourses.map((course) => (
              <Card key={course.id}>
                <img
                  src={course.image}
                  alt={course.title}
                  width={400}
                  height={300}
                  className="w-full h-48 object-cover rounded-t-lg"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-bold">{course.title}</h3>
                  <p className="text-muted-foreground line-clamp-2 mb-4">
                    {course.description}
                  </p>
                  <div className="flex items-center justify-between">
                    <Badge variant="secondary" className="text-xs">
                      {course.category}
                    </Badge>
                    <Badge variant="outline" className="text-xs">
                      {course.difficulty}
                    </Badge>
                  </div>
                </CardContent>
                <CardFooter className="grid ">
                  <div className="grid grid-cols-2  ">
                    <span className=" font-bold text-lg">
                      ${course.price.toFixed(2)}
                    </span>
                    <span className=" font-bold text-lg mr-0 ">
                    <Link
                      href="/auth/courseD"
                      className="rounded-md bg-primary px-3.5 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm hover:bg-primary/90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
                      prefetch={false}
                    >Enroll now
                      </Link>  
                    </span>
                  </div>
                </CardFooter>
              </Card>
            ))}
          </div>
        </div>
      </section>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">
          &copy; 2024 Acme Courses. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
